imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    property_info: true
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

monolog:
    channels: ['search']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../migrations"
    namespace: App\Migrations
    table_name: migration
    name: Mediatok Migrations

fos_js_routing:
    routes_to_expose: [ app_api_formats_by_types, app_api_fields_by_types ]

old_sound_rabbit_mq:
    connections:
        default:
            host: "%queue_host%"
            port: "%queue_port%"
            user: "%queue_user%"
            password: "%queue_password%"
            vhost: "%queue_vhost%"
            lazy: false
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        export:
            connection: default
            exchange_options: {name: 'export', type: direct}
        search:
            connection: default
            exchange_options: {name: 'search', type: direct}
    consumers:
        export:
            connection: default
            exchange_options: {name: 'export', type: direct}
            queue_options: {name: 'export'}
            callback: AppBundle\Consumer\Export
        search:
            connection: default
            exchange_options: {name: 'search', type: direct}
            queue_options: {name: 'search'}
            callback: AppBundle\Consumer\Search
